### ISSUE TITLE
Umbrella header 'Realm.h' not found

### ISSUE THREAD

**Issue by knot2nice** [fetlife/fetlife-ios#27] opened 2016-05-28 22:08 UTC
Followed the instructions...hit build. keep getting this error: "Umbrella header 'Realm.h' not found"

**Comment by knot2nice** [comment] 2016-05-28 22:31
```
sudo gem uninstall cocoapods
sudo gem install cocoapods -v 0.39.0
pod install
```

there seems to be an issue with the latest version of cocoapods https://www.bountysource.com/issues/34168337-cocoapods-error-on-os-x-umbrella-header-realm-h-not-found

this fixed it...now trying to fix this error "An App ID with Identifier 'co.bitlove.opensource.FetLife' is not available. Please enter a different string."

**Comment by ellteeelltee** [comment] 2016-05-28 22:37
The string in question is assigned by apple to the bitlove developer account. You have to make one up yourself that then will be associated with your dev account. Something like "co.knot2nice.fetlifeapp should work, as long as it's unique

**Comment by knot2nice** [comment] 2016-05-28 22:40
done and worked. ...that was a lot of work for a conversations app >.< rofl

lastly you may want to change the git clone address to the http version. i couldnt use the ssh link since you dont have my public key

**Comment by kidou99** [comment] 2016-05-29 10:16
That Realm.h error really had me scratching my head. I found doing a "pod update" resolved that error, but then the build would abort with some other errors (I guess the library interface changes in the later pods). I didn't think to try downgrading cocoapods :-) At least it now works, and I'm in a position to help with testing (will need to learn about ObjectiveC/iOS development before I'll be in a position to contribute any code)

**Comment by eebean2** [comment] 2016-05-31 03:24
Run `pod update` AFTER `pod install` as it didn't pull all the correct pod versions. I troubleshooted this myself for a while. (like kidou99 said)

Apparently the issue is fixed in version 1.0.0 of Realm, but it only pulls up to 0.98.x on install.

**Comment by jacortinas** [comment] 2016-06-13 21:53
Hey sorry this took so long to get to, PR #28 has been merged and this issue should be fixed. If there is still any issue I would be happy to help figure that out. 😄

**Comment by jacortinas** [comment] 2016-06-15 16:11
Closing this issue as it should be fixed. 💃

**Closed by jacortinas** 2016-06-15 16:11 UTC
